project:
  type: book
  output-dir: _book

book:
  title: MandaRama
  author:
    - name: Koen Derks
  chapters:
    - index.qmd

format:
  pdf:
    geometry:
      - twoside
      - left = 5mm
      - right = 5mm
      - bottom = 5mm
      - top = 5mm
      - paperwidth = 210mm
      - paperheight = 210mm
    fontfamily: libertinus
    toc: false
    number-sections: false
