project:
  type: book
  output-dir: _book

book:
  title: "Genigma: Generative Puzzles"
  author:
    - name: Koen Derks
  chapters:
    - index.qmd
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: front-page.png
  site-url: https://koenderks.github.io/genigma/
  repo-url: https://github.com/koenderks/genigma/
  repo-branch: master
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  open-graph: true
  page-navigation: false
  reader-mode: true
  search: false
  twitter-card:
    image: "front-page.png"

format:
  html:
    theme: cosmo

  pdf:
    documentclass: book
    include-in-header:
      - text: |
          \pagenumbering{arabic}
          \usepackage{tikz}
          \renewcommand{\frontmatter}{%
              \thispagestyle{empty}%
              \begin{tikzpicture}[remember picture,overlay]
              \node at (current page.center) {\includegraphics[width=\paperwidth,height=\paperheight,keepaspectratio]{front-page.pdf}};
              \end{tikzpicture}%
          }
          \renewcommand{\backmatter}{%
              \thispagestyle{empty}%
              \begin{tikzpicture}[remember picture,overlay]
              \node at (current page.center) {\includegraphics[width=\paperwidth,height=\paperheight,keepaspectratio]{back-page.pdf}};
              \end{tikzpicture}%
          }
          \renewcommand{\mainmatter}{\clearpage}
          \renewcommand{\maketitle}{}
          \renewcommand{\chapter}{}
          \usepackage{fancyhdr}
          \pagestyle{fancy}
          \renewcommand{\headrulewidth}{0pt} % Remove header line
          \fancyhf{}
          \fancyfoot[C]{\thepage}
    geometry:
      - twoside
      - left = 5mm
      - right = 5mm
      - bottom = 10mm
      - top = 12.5mm
      - paperwidth = 148.5mm
      - paperheight = 210mm
      - includefoot
    toc: false
    number-sections: false
