project:
  type: book
  output-dir: _book

book:
  title: "Genigma: Generative Puzzles"
  author:
    - name: Koen Derks
  chapters:
    - index.qmd
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: front-page.svg
  favicon: front-page.png
  site-url: https://koenderks.github.io/genigma/
  repo-url: https://github.com/koenderks/genigma/
  repo-branch: master
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  open-graph: true
  page-navigation: false
  reader-mode: false
  search: false
  twitter-card:
    image: "front-page.svg"

format:
  html:
    toc: false
    theme:
      - cosmo

  pdf:
    geometry:
      - twoside
      - left = 5mm
      - right = 5mm
      - bottom = 15mm
      - top = 15mm
      - paperwidth = 148.5mm
      - paperheight = 210mm
    fontfamily: libertinus
    toc: false
    number-sections: false
