```{r echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.show = "hold",
  fig.align = "center",
  fig.width = 12,
  fig.height = 12,
  out.width = NULL
)
source("./R/generate_mandala.R")
source("./R/generate_sudoku.R")
source("./R/generate_wordfinder.R")
```

::: {.content-visible when-format="html"}
Welcome to this generative puzzle book! Created using the open-source programming language R, this book is completely [free](https://www.gnu.org/philosophy/free-sw.html)! And here's the best part: it never runs out! If you're craving more puzzles, just come back tomorrow. This book refreshes itself every day, offering you 9 brand-new mandalas and 9 sudoku to enjoy.
:::

```{r echo = FALSE, message=FALSE}
if (!knitr::is_html_output()) {
    seed <- sample.int(.Machine$integer.max, 1)
	set.seed(seed)
    p1 <- generate_mandala(labels = TRUE)
    set.seed(seed)
    p2 <- generate_mandala(colors = TRUE)
    gridExtra::grid.arrange(p2, p1, layout_matrix = matrix(c(
      2, 2, 2, 2, NA,
      2, 2, 2, 2, NA,
      2, 2, 2, 2, NA,
      2, 2, 2, 1, 1,
      NA, NA, NA, 1, 1
    ), byrow = TRUE, nrow = 5, ncol = 5), top=grid::textGrob("Mandala", gp = grid::gpar(fontsize = 40, fontfamily = "sans", fontface = "bold")))
}
```
\newpage

```{r echo = FALSE, message=FALSE}
if (!knitr::is_html_output()) {
	set.seed(seed)
	generate_sudoku()
}
```
\clearpage

```{r echo = FALSE, message=FALSE}
if (!knitr::is_html_output()) {
	set.seed(seed)
	generate_sudoku(answers = TRUE)
}
```
\clearpage

```{r echo = FALSE, message=FALSE}
if (!knitr::is_html_output()) {
	set.seed(seed)
	generate_wordfinder()
}
```
\clearpage

```{r echo = FALSE, message=FALSE}
if (!knitr::is_html_output()) {
	set.seed(seed)
	generate_wordfinder(answers = TRUE)
}
```
\clearpage

